---

name: "anisf.docx_templates.simple_run"

on:
  push:

jobs:
  python:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
    strategy:
      fail-fast: false
      matrix:
        operations:
        - liquidation
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: anisf/docx_templates/simple_run

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      working-directory: anisf/docx_templates/simple_run
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: anisf/docx_templates/simple_run
      run: |
        python gen_docs.py ${{ matrix.operations }}
